default: true
MD013: false
MD033:
  allowed_elements:
    - summary
    - details
MD024:
  siblings_only: true
MD025:
  front_matter_title: ""
MD028: false # no blank lines in block quote - disabling b/c it fires on 2 consecutive block quotes :/

