default: true
MD013: false
MD033:
  allowed_elements:
    - summary
    - details
    - br
    - li
    - ul
MD024:
  siblings_only: true
MD025:
  front_matter_title: ""
MD028: false # no blank lines in block quote - disabling b/c it fires on 2 consecutive block quotes :/
# MD060: false # table column style (compact vs aligned) - can disable if table formatting becomes a maintenance burden

