name: Publish repo_parser image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - tools/repo_parser/**

permissions: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/repo_parser

jobs:
  build-and-push:
    name: Build and push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6.0.3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4.3.0 # Immutable tag - https://github.com/docker/login-action/releases/tag/v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6.1.0 # Immutable tag - https://github.com/docker/metadata-action/releases/tag/v6.1.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v7.3.0 # Immutable tag - https://github.com/docker/build-push-action/releases/tag/v7.2.0
        with:
          context: tools/repo_parser
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
