FROM cgr.dev/chainguard/python:latest-dev
# FROM busybox

WORKDIR .

COPY ./spec_finder.py ./
VOLUME /appdir
# CMD spec_finder.py /appdir
# ENTRYPOINT ["python3", "./spec_finder.py", "--code-directory", "/appdir"]
